### ISSUE TITLE
ngrok FTP tunneling issue

### ISSUE THREAD

**Issue by OmarTrigui** [inconshreveable/ngrok#373]
I have installed many FTP Servers on a Windows machine and set ngrok for FTP tunneling.

    C:\path\to\ngrok> ngrok tcp 21

Using linux, i am able to establish an FTP connection and browse the directories ONLY with the installed ftp client.

    $ ftp 
    ftp> open 0.tcp.ngrok.io port_here

The problem is that FileZilla, Classic FTP File Transfer Software, Chrome & Firefox extensions, failed.

FileZilla output: 

    Command:	LIST
    Response:	150 Opening ASCII mode data connection
    Error:	Connection timed out after 20 seconds of inactivity
    Error:	Failed to retrieve directory listing

I wonder why i can't browse using FileZilla, but with the ftp Linux command works well.

Thank you.

**Comment by pyhedgehog** [comment]
Problem cause is that ftp protocol uses several (two at once) communication channels - one for control (commands and replies) and another for data (file transfer and directory listing). This can be resolved by using "passive mode" (when server connects to client for data channel), but not in case where both server and client are behind firewall (which is usual case for using ngrok).

**Comment by OmarTrigui** [comment]
Thank you for the useful hints.
Problem solved in FileZilla via : Edit > Settings > Connection > FTP > Passive mode, and selecting "Fall back to active mode"
Bingo !

**Comment by inconshreveable** [comment]
thanks @pyhedgehog !

**Comment by natsu90** [comment]
Hi @OmarTrigui, i tried your solution but still getting same error. any idea?

**Comment by pyhedgehog** [comment]
@natsu90, switch to some other protocol. I've described why ftp will not work. I think that OmarTrigui uses it in case where either peers are in same net or one of peers accessible from outside.

WebDav will work in most cases and there are gateways to FTP.
